version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      # - "80:80"
      # - "443:443"
      - "8000:8000"
      - "8082:8081"

    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./src/static:/static
      - ./src/static/MEDIA:/MEDIA

    depends_on:
      - storyconnect

  storyconnect:
    build: .
    container_name: storyconnect
    command: |-
      bash -c "python manage.py migrate && 
      python manage.py collectstatic --noinput && 
      gunicorn storyconnect.wsgi:application --bind 0.0.0.0:8000 --reload --timeout 30"
    volumes:
      - ./src/storyconnect:/src
      - ./src/storyconnect/static:/static
    expose:
      - "8000"

  jenkins:
    image: dall18/flutter_jenkins:buildx-latest
    privileged: true
    user: root
    environment:
      # Uncomment JENKINS_OPTS to add prefix: e.g. https://127.0.0.1:8443/jenkins
      - JENKINS_OPTS="--prefix=/jenkins"
    expose:
      - "8080"
      - "50000"
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
