# Generated by Django 4.2.4 on 2023-09-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textselection',
            old_name='floatng',
            new_name='floating',
        ),
    ]

