# Generated by Django 4.2.5 on 2023-10-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_writerfeedback_remove_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerfeedback',
            name='sentiment',
            field=models.IntegerField(blank=True, choices=[(0, 'great'), (1, 'good'), (2, 'mediocre'), (3, 'bad')], null=True),
        ),
    ]
