# Generated by Django 4.2.5 on 2023-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_announcement_profile_delete_userinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='Display Name not set', max_length=255, unique=True),
        ),
    ]
