# Generated by Django 4.2.5 on 2023-11-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
