# Generated by Django 4.2.5 on 2023-11-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_profile_image_url_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
