# Generated by Django 4.2.4 on 2023-10-20 08:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_book_status'),
        ('features', '0002_genretagging_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genretagging',
            name='book_title_len',
        ),
        migrations.RemoveField(
            model_name='genretagging',
            name='chapter_number',
        ),
        migrations.RemoveField(
            model_name='genretagging',
            name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='genretagging',
            name='content',
        ),
        migrations.RemoveField(
            model_name='genretagging',
            name='summary_char_len',
        ),
        migrations.RemoveField(
            model_name='genretagging',
            name='summary_len',
        ),
        migrations.RemoveField(
            model_name='genretagging',
            name='title_char_len',
        ),

    ]
