# Generated by Django 4.2.4 on 2023-10-23 16:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_book_status'),
        ('features', '0003_remove_genretagging_book_title_len_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_chapter_len', models.IntegerField(default=0)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.chapter')),
            ],
        ),
    ]
