# Generated by Django 4.2.5 on 2023-11-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_chapter_chapter_title'),
        ('features', '0004_chaptertagging'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreTagging',
            new_name='GenreTag',
        ),
    ]
