# Generated by Django 4.2.5 on 2023-11-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_chapter_chapter_title'),
        ('features', '0005_rename_genretagging_genretag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreTag',
            new_name='GenreTagging',
        ),
    ]
