# Generated by Django 4.2.5 on 2023-12-03 19:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_alter_chaptertagging_genre_alter_genretagging_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptertagging',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='genretagging',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
