name: storyconnect
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  beamer: ^1.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  json_annotation: ^4.8.0
  tuple: ^2.0.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

