# Generated by Django 4.2.4 on 2023-09-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_alter_book_copyright_alter_book_target_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadUnblockerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('suggestion_type', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_unblocker_suggestions', to='books.chapter')),
            ],
        ),
    ]
