# Generated by Django 4.2.5 on 2023-10-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_statementsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsheet',
            name='last_run_response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statementsheet',
            name='last_run_chapter',
            field=models.IntegerField(default=0),
        ),
    ]
