# Generated by Django 4.2.5 on 2023-10-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_narrativeelement_narrativeelementattribute_and_more'),
        ('ai_features', '0003_statementsheet_last_run_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_summary', to='books.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='')),
                ('last_sum_chapter', models.IntegerField(default=-1)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_summary', to='books.book')),
            ],
        ),
    ]
