version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_storyconnect
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./backend/static:/static
      - ./frontend/storyconnect/build/web:/usr/share/nginx/flutter

    depends_on:
      - storyconnect

  storyconnect:
    build: .
    container_name: storyconnect
    env_file:
      - .env       
    command: |-
      bash -c "python manage.py migrate && 
      python manage.py collectstatic --noinput && 
      python -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/storyconnect:/src
      - ./backend/storyconnect/static:/static
    expose:
      - "8000"
    ports:
      - "5678:5678"
