# Generated by Django 4.2.5 on 2023-12-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0016_alter_book_synopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Based_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.IntegerField(blank=True, null=True)),
                ('tmp', models.CharField(blank=True, default='', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='User_Based_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.library')),
                ('recommendations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_rec.book_based_rec')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
