# Generated by Django 4.2.5 on 2023-11-20 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_based_rec',
            name='recommendations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user_based_rec',
            name='recommendations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
