# Generated by Django 4.1.7 on 2023-09-06 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.IntegerField(choices=[(1, 'Complete'), (2, 'In progress')], default=2),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
