# Generated by Django 4.1.7 on 2023-09-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_book_status_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.IntegerField(choices=[(1, 'Complete'), (2, 'In progress')], default=2, null=True),
        ),
    ]
