# Generated by Django 4.2.4 on 2023-09-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_copyright_alter_book_target_audience'),
        ('books', '0006_alter_book_book_status'),
    ]

    operations = [
    ]
