# Generated by Django 4.2.4 on 2023-09-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_merge_20230927_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
