# Generated by Django 4.2.5 on 2023-10-18 02:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_merge_20230927_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrativeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, upload_to='elements/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeElementAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, max_length=100)),
                ('confidence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeElementAttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='book',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='library',
            name='status',
            field=models.IntegerField(choices=[(1, 'Reading'), (2, 'Completed'), (3, 'To Read')]),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
        migrations.AddField(
            model_name='narrativeelementattributetype',
            name='applicable_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.narrativeelementtype'),
        ),
        migrations.AddField(
            model_name='narrativeelementattributetype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='narrativeelementattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.narrativeelementattributetype'),
        ),
        migrations.AddField(
            model_name='narrativeelementattribute',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.narrativeelement'),
        ),
        migrations.AddField(
            model_name='narrativeelement',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.narrativeelementtype'),
        ),
        migrations.AddField(
            model_name='narrativeelement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
