# Generated by Django 4.2.5 on 2023-10-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_narrativeelement_narrativeelementattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, null=True),
        ),
    ]
