# Generated by Django 4.2.5 on 2023-11-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
