# Generated by Django 4.2.5 on 2023-11-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='raw_content',
            field=models.TextField(blank=True),
        ),
    ]
