# Generated by Django 4.2.5 on 2023-11-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_chapter_raw_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner',
            new_name='user',
        ),
    ]
