# Generated by Django 4.2.5 on 2023-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_rename_owner_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
