# Generated by Django 4.2.5 on 2023-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
